{
 "title": "Observability Lab",
 "tags": [
  "observability",
  "spring-boot",
  "portfolio"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Status da Aplicação",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"observability-lab\"}",
     "legendFormat": "UP/DOWN"
    }
   ]
  },
  {
   "title": "Requisições por Segundo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{application=\"observability-lab\"}[1m])",
     "legendFormat": "{{uri}} - {{method}}"
    }
   ]
  },
  {
   "title": "Latência Média por Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"observability-lab\"}[1m]) / rate(http_server_requests_seconds_count{application=\"observability-lab\"}[1m])",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Taxa de Erros (5xx) por Minuto",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{application=\"observability-lab\", status=~\"5..\"}[1m])",
     "legendFormat": "Erros {{uri}}"
    }
   ]
  },
  {
   "title": "Memória JVM Usada",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"observability-lab\", area=\"heap\"}",
     "legendFormat": "Heap - {{id}}"
    }
   ]
  },
  {
   "title": "CPU da Aplicação (process)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_usage{application=\"observability-lab\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Contagem Total de Erros Simulados",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "app_errors_total{application=\"observability-lab\"}",
     "legendFormat": "Erros Simulados"
    }
   ]
  }
 ]
}